version: '2'
services:
  db:
    image: mongo
    volumes: 
      # - /mnt/var/lib/mongo/db:/data/db
      - ./remote_api/scripts:/tmp/scripts
  mq:
    image: rabbitmq
    ports: 
      - "15672:15672"
  remote_api:
    build: remote_api
    environment:
      NODE_ENV: development
    # volumes:
    #   - ./remote_api:/remote_api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mq
    entrypoint: ./wait-for-it.sh db:27017 --strict -- node app.js
  dispatcher:
    build: dispatcher
    # volumes:
    #   - ./dispatcher:/dispatcher
    ports:
      - "3030:3030"
    depends_on:
      - mq
      - db
    entrypoint: ./wait-for-it.sh db:27017 --strict -- node app.js
  
